title: Freckled Florist
baseurl:            "/another-mothers-cookies/"
url:                "https://jjoocceeee.github.io/another-mothers-cookies/"

# Social Profiles
facebook_username:  anothermotherscookies
instagram_username: anothermotherscookies

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
theme: jekyll-theme-clean-blog
collections:
  pages:
    output: true
    permalink: /:collection/:title
